### ISSUE TITLE
Support Resource Groups with "Region-less" Naming Convention?

### ISSUE THREAD

**Issue by bdschaap** [HomecareHomebase/azure-bake#100]
I'm defining some centralized resources (not region specific).  One is for ActionGroups which use a 'Global' location.  The other is for Application Insights and we're centralizing telemetry in a single region.  I'd appreciate any thoughts on whether to allow resource groups to optionally include the region in the naming convention.  It's supported for resources but not resource groups.

It should be possible to do this by using an expression for the rgOverride field but https://github.com/HomecareHomebase/azure-bake/issues/93 would need to be addressed.

**Comment by bdschaap** [comment]
@csperbeck brought this up again when reviewing one of my Azure resource deployments

**Comment by whilke** [comment]
This is already supported coreutils.resource_group(<name>, false)

you'll get RG_<name>__<env>

notice the two __  between name and env since we are not setting a region code string. Someone could submit a PR to fix that to a single _ if rgn is not set in _create_resource_group_name

**Comment by whilke** [comment]
Reopening because I understand what you are talking about now. You want the package auto RG creation to support a region-less creation option. Fix inc.
