### ISSUE TITLE
Boolean variables not supported in recipes

### ISSUE THREAD

**Issue by kevinreillyhchb** [HomecareHomebase/azure-bake#27]
Trying to pass a boolean parameter into a recipe results in a template validation error.

(example from trying to create an Azure Container Registry with @azbake/ingredient-arm)
```
[Mon, 04 Mar 2019 21:19:58 GMT] East US Baking recipe azure-container-registry
[Mon, 04 Mar 2019 21:19:58 GMT] East US : acr adding ingredient type[@azbake/ingredient-arm] source[./acr-arm.json]
[Mon, 04 Mar 2019 21:19:58 GMT] East US : acr deployment for custom arm template: ./acr-arm.json
[Mon, 04 Mar 2019 21:19:58 GMT] East US : acr param: registryName=testacr
[Mon, 04 Mar 2019 21:19:58 GMT] East US : acr param: adminUserEnabled=false
[Mon, 04 Mar 2019 21:19:58 GMT] East US : acr param: registryLocation=eastus
[Mon, 04 Mar 2019 21:19:58 GMT] East US : acr param: registrySku=basic
[Mon, 04 Mar 2019 21:19:58 GMT] East US : acr starting arm deployment for template
[Mon, 04 Mar 2019 21:19:58 GMT] East US : acr validating deployment...
[Mon, 04 Mar 2019 21:20:00 GMT] East US : acr Validation failed (InvalidTemplate)
Message: Deployment template validation failed: 'The provided value for the template parameter 'adminUserEnabled' at line '1' and column '309' is not valid.'.
```

**Comment by csperbeck** [comment]
The following [URL](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-logical#bool) will give you the ARM syntax to transform a true/false string to `bool`.

**Comment by whilke** [comment]
Can you test this against the latest bake release? I believe this should be fixed now (to support non-string types as arm template parameters)

**Comment by bdschaap** [comment]
I ran across this for integer and boolean variables earlier today using the your commit from yesterday.  They're optional params so I left them out for the time being.

I believe the int was failing on this code "let check = variable.Code.trim()".

[Fri, 12 Apr 2019 18:25:06 GMT] East US : ehndiag-deploy deployment failed: TypeError: variable.Code.trim is not a function
[Fri, 12 Apr 2019 18:25:06 GMT] TypeError: variable.Code.trim is not a function
[Fri, 12 Apr 2019 18:25:06 GMT] East US Error


I believe the bool was failing validation when the arm client submits it for validation.

[Fri, 12 Apr 2019 18:31:46 GMT] East US : ehndiag-deploy Validation failed (InvalidTemplate)
Message: Deployment template validation failed: 'The provided value for the template parameter 'kafkaEnabled' at line '1' and column '409' is not valid.'.
[Fri, 12 Apr 2019 18:31:46 GMT] East US : ehndiag-deploy deployment failed: Error: validate failed
[Fri, 12 Apr 2019 18:31:46 GMT] East US : ehndiag-deploy deployment failed: Error: validate failed
[Fri, 12 Apr 2019 18:31:46 GMT] Error: validate failed
[Fri, 12 Apr 2019 18:31:46 GMT] East US Error

**Comment by bdschaap** [comment]
There seems to be a related issue.  The problem I had today was with Bake variables (as opposed to parameters).  What's strange is that **_true_** works but _**false**_ doesn't.  Setting the variable to false causes the variable to not be set at all.

**Comment by bdschaap** [comment]
Came across this issue again.  Setting a Bake variable to `false` causes it to be evaluated as a blank string.

![image](https://user-images.githubusercontent.com/19688458/60363931-ce8baf00-99b2-11e9-8618-a35b35463188.png)

**Comment by whilke** [comment]
bake variables now pass through the source type. If the source value comes from a BAKE_VARIABLE (env variable) you will need to use coreutils.toBool() to cast correctly since all env vars come in as strings.

**Comment by bdschaap** [comment]
I believe this is fixed in https://github.com/HomecareHomebase/azure-bake/pull/140.
