### ISSUE TITLE
Tags for Resources do not appear to be supported

### ISSUE THREAD

**Issue by csperbeck** [HomecareHomebase/azure-bake#28]
Tags, key/value pairs for resource organization do not appear to be supported. Example tag:

```
"tags": {
            "Deployment": "1.7.0-rc.2-2",
            "Parent": "hchb_container_registry"
}
```

**Comment by whilke** [comment]
Tags are on the backlog for next iteration

**Comment by whilke** [comment]
if you mean bake resource tags

**Comment by whilke** [comment]
Auto-injected tags are now part of the system. All azure resources created will get a set of pre-defined tags, and ingredient authors can expose custom tags if they want as well
