### ISSUE TITLE
Bake does not appear to support integers

### ISSUE THREAD

**Issue by csperbeck** [HomecareHomebase/azure-bake#46]
Integers added unquoted in the template are not supported currently and the arm template cannot accomodate an integer added as a string.

**Comment by bdschaap** [comment]
What this Bake parameters or variables?  I noticed that I am able to use integers for Bake variables.

**Comment by whilke** [comment]
literal ints work now. Values from util functions should also stick. The only thing that forces strings are global bake variables since they come from env vars and those are always string values. We need to add some corutil cast functions to help solve that.

**Comment by whilke** [comment]
coreutils now has toInt/toBool/etc.
